server:
  port: 8888

spring:
  dynamic:
    tp:
      config-type: properties
      etcd:
        endpoints: http://127.0.0.1:2379
        auth-enable: false
        key: /config/dynamic-tp-etcd-demo
  application:
    name: dynamic-tp-etcd-demo

management:
  endpoints:
    web:
      exposure:
        include: '*'   # 测试使用，线上不要用*，按需开启
  prometheus:
    metrics:
      export:
        enabled: true